# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.blacklistedKernelModules = [ "b43" "bcma" "brcmsmac" "brcmfmac" "ssb" ];
  nixpkgs.config.permittedInsecurePackages = [
    "broadcom_sta"
  ];
  boot.extraModulePackages = [
    (config.boot.kernelPackages.broadcom_sta.overrideAttrs (old: {
      meta = old.meta // { knownVulnerabilities = []; };
    }))
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "wl" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  hardware.enableAllHardware = true;
  hardware.enableAllFirmware = true;
  hardware.enableRedistributableFirmware = true;

  fileSystems."/" =
    { device = "/dev/mapper/luks-0c9573d3-2fe3-4962-bbe9-5db94b3f1ace";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0c9573d3-2fe3-4962-bbe9-5db94b3f1ace".device = "/dev/disk/by-uuid/0c9573d3-2fe3-4962-bbe9-5db94b3f1ace";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F7E9-87DF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  networking.networkmanager.enable = true;

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
